### PR TITLE
add history page

### PR DESCRIPTION
**Pull request by mojavelinux**

### CODE REVIEW

**Comment by mojavelinux** [comment]
I'm going to leave this open until we finish collecting all the history and have a complete story to tell.

**Comment by mojavelinux** [comment]
@Mogztter Feel free to add information to the history summary or timeline.

**Comment by Mogztter** [comment]
It is kind of amazing to look back and see all the work we have done as a community 🤯
I think you did a great job, all the key milestones are there.

Maybe we could emphasis on growth by adding entries when we hit a big number. For instance, `asciidoctor` 10 millions nth downloads and/or when the project hit 100 contributors and/or 3000 stars, etc...
We might also add a few recognized/leading companies that adopted AsciiDoc/Asciidoctor as their primary tool for documentation.

**Comment by Mogztter** [comment]
@mojavelinux If you want to edit the timeline, you can import the file `asciidoc-history.json` at https://excalidraw.com.

**Comment by mojavelinux** [comment]
The diagram is a great idea.

Let's try to identify what we are missing for the first revision of this page. What key events are we missing?

**Comment by mojavelinux** [comment]
The JSON file seems to have more detail than the list in the AsciiDoc file. @Mogztter could you fill in some of those key events?

**Comment by mojavelinux** [comment]
> but maybe we could use an SVG image?

Absolutely.

**Comment by mojavelinux** [comment]
I'm not sure I like the loose entries with arrows at the top of the graph because it looks busy. But I'm not also sure where else to place them. I also feel like the Maven and Gradle plugins need more tangible entries, but not a whole row. I wonder if they can be grouped into the AsciidoctorJ row somehow.

**Comment by mojavelinux** [comment]
Here are the first and last commits of asciidoc.rb in the git-scm repository, which is where the origins of parsing AsciiDoc in Ruby began:

* https://github.com/git/git-scm.com/blob/5a5edecfc2c4a1bcff86af432e062d2c6f860bed/lib/asciidoc.rb
* https://github.com/git/git-scm.com/blob/ab9efdc8d95c65b9e74954a4847de8b8f98486fb/lib/asciidoc.rb

**Comment by Mogztter** [comment]
> I'm not sure I like the loose entries with arrows at the top of the graph because it looks busy. 

I can try to add dots on lines.
I like the "bloom" effect of the loose entries (i.e. projects are flourishing everywhere) but yeah it's a bit messy

**Comment by mojavelinux** [comment]
I'm going to pull the diagram out into a separate PR so we can move forward with merging the history page.

**Pull request merged**
